
[[_configuration]]
= Configuration
:groupId: org.codehaus.griffon.plugins

The plugin delivers artifacts for both Swing and JavaFX. It also contains Groovy enhancements
that can be used in combination with the respective UI toolkit DSL (SwingBuilder and GroovyFX).

== Gradle

You have two options for configuring this plugin: automatic and manual.

=== Automatic

As long as the project has the `org.codehaus.griffon.griffon` plugin applied to it you
may include the following snippet in +build.gradle+

[source,groovy,options="nowrap"]
[subs="attributes"]
----
dependencies {
    griffon '{groupId}:griffon-crystalicons-plugin:{project-version}'
}
----

The `griffon` plugin will take care of the rest given its configuration.

=== Manual

You will natcow to configure any of the following blocks depending on your setup

.Java + Swing
[source,groovy,options="nowrap"]
[subs="attributes"]
----
dependencies {
    compile '{groupId}:griffon-crystalicons-swing:{project-version}'
}
----

.Java + JavaFX
[source,groovy,options="nowrap"]
[subs="attributes"]
----
dependencies {
    compile '{groupId}:griffon-crystalicons-javafx:{project-version}'
}
----

.Groovy + Swing
[source,groovy,options="nowrap"]
[subs="attributes"]
----
dependencies {
    compile '{groupId}:griffon-crystalicons-swing-groovy:{project-version}'
}
----

.Groovy + JavaFX
[source,groovy,options="nowrap"]
[subs="attributes"]
----
dependencies {
    compile '{groupId}:griffon-crystalicons-javafx-groovy:{project-version}'
}
----

== Maven

First configure the `griffon-crystalicons-plugin` BOM in your POM file, by placing the following
snippet before the `<build>` element

[source,xml,options="nowrap"]
[subs="attributes,verbatim"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>{groupId}</groupId>
            <artifactId>griffon-crystalicons-plugin</artifactId>
            <version>{project-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Next configure dependencies as required by your particular setup

.Java + Swing
[source,xml,options="nowrap"]
[subs="attributes,verbatim"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>griffon-crystalicons-swing</artifactId>
</dependency>
----

.Java + JavaFX
[source,xml,options="nowrap"]
[subs="attributes,verbatim"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>griffon-crystalicons-javafx</artifactId>
</dependency>
----

.Groovy + Swing
[source,xml,options="nowrap"]
[subs="attributes,verbatim"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>griffon-crystalicons-swing-groovy</artifactId>
</dependency>
----

.Groovy + JavaFX
[source,xml,options="nowrap"]
[subs="attributes,verbatim"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>griffon-crystalicons-javafx-groovy</artifactId>
</dependency>
----

